name: Deploy Maven artifact to Nexus Repository OSS

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create settings.xml
        shell: bash
        run: |
          echo "${{ secrets.SETTINGS_XML_DEPLOY }}" > settings.xml

      - name: Import Ainoha Framework GPG key
        shell: bash
        run: |
          echo "${{ secrets.GPG_KEY }}" > ainoha-gpg.key
          gpg --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import ainoha-gpg.key

      - name: Deploy Maven artifact
        shell: bash
        run: |
          mvn -B -s settings.xml deploy -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"