name: Run tests with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 11, 12, 13, 14, 15 ]
    name: Test with Java ${{ matrix.java }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run tests with Maven
        run: |
          mvn -B clean test